# INPUT OUTPUT STRING MANIPULATION 
# INPUT EXAMPLE :
boy_name = input("boy name :")
girl_name = input("girl name :")
print( boy_name  +  "and "  + girl_name  + " are good friends.")

# so this is the example of input  and output string manipulation.
# if input is an integer ?
# example code :
boy_name = input("boy name :")
girl_name = input("girl name :")
boy_age = int(input(" age : "))
girl_age = int(input(" age : "))
age_difference = boy_age - girl_age
print(f"{boy_name}  and  {girl_name} are good friends. their age difference is {age_difference} ")

# triple quotes can be used in python for multi line strings.
# multi_line_string = """ this is a multi line string.

# ''' this triple quotes can be ignored by interpreter.'''
# so we can use triple quotes for multi line comments."""